name: Publish on Docker Hub and Deploy

on:
  release:
    types: [published]


jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi



  build_and_pub:
    needs: [run_tests]  
    runs-on: [ubuntu-latest]

    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      

    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:10} -f Dockerfile .
      
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:10}
